export const CASE_NAME_EN_MAP: Record<string, string> = {
  "Мусорка Залупы": "Zalupa Trash Crate",
  "10% Нож": "10% Knife Chance",
  "50% Нож": "50% Knife Chance",
  "Только Ножи": "Knives Only",
  "Всё или Ничего": "All or Nothing",
  "Охота на Dragon Lore": "Dragon Lore Hunt",
  "Перчатки VIP": "VIP Gloves",
  "AWP & Снайперки": "AWP & Snipers Elite",
  "AK-47 Вселенная": "AK-47 Universe",
  "M4A4 & M4A1-S Элит": "M4A4 & M4A1-S Elite",
  "Printstream Лаборатория": "Printstream Laboratory",
  "Кейс Азимов": "Asiimov Mania",
  "Hyper Beast Зверинец": "Hyper Beast Menagerie",
  "Fade & Градиент": "Fade Gradient",
  "Doppler Лихорадка": "Doppler Fever",
  "Поверхностная Закалка": "Case Hardened Vault",
  "Красная Линия": "Redline Rush",
  "Неоновый Киберпанк": "Neon Cyberpunk",
  "Статтрек Арсенал": "StatTrak Arsenal",
  "Тайный Арсенал": "Classified Arsenal",
  "Desert Eagle Ваншот": "Desert Eagle One-Shot",
  "Пистолетный Раунд": "Pistol Round",
  "Бабочка Мечты": "Butterfly Dreams",
  "Керамбит Эксклюзив": "Exclusive Karambit",
  "Штык-нож M9 Элита": "M9 Bayonet Elite",
  "Бюджетный 50 DC": "Budget 50 DC",
  "Бюджетный 100 DC": "Budget 100 DC",
  "Бюджетный 250 DC": "Budget 250 DC",
  "Бюджетный 500 DC": "Budget 500 DC",
  "Студент 750 DC": "Student 750 DC",
  "Стипендия 1000 DC": "Stipend 1,000 DC",
  "Получка 2500 DC": "Paycheck 2,500 DC",
  "Аванс 5000 DC": "Advance 5,000 DC",
  "Зарплата 10000 DC": "Salary 10,000 DC",
  "Олигарх 25000 DC": "Oligarch 25,000 DC",
  "Миллионер 50000 DC": "Millionaire 50,000 DC",
  "Шейх 100000 DC": "Sheikh 100,000 DC",
  "SMG Раш Б": "SMG Rush B",
  "Тяжелая Артиллерия": "Heavy Artillery",
  "Легенды Контры": "CS Legends",
  "Кейс Оперативников": "CS2 Agents Case",
  "Нож Коготь Тигр": "Talon Knife Tiger",
  "Скелетный Нож Призрак": "Skeleton Knife Ghost",
  "Стилет Итальянский": "Italian Stiletto",
  "Нож Бродяга Номад": "Nomad Survival Knife",
  "Нож Медведь Урсус": "Ursus Brutal Knife",
  "Паракорд Рейнджер": "Paracord Ranger",
  "Нож Выживания Охотник": "Hunter Survival Knife",
  "Кукри Шторм": "Kukri Storm",
  "Складной Нож Элегант": "Flip Knife Elegant",
  "Охотничий Нож Тактик": "Tactical Huntsman",
  "Нож Боуи Титан": "Bowie Titan",
  "Тычковые Ножи": "Shadow Daggers",
  "Нож с крюком": "Gut Knife Club",
  "Дамасская Сталь": "Damascus Steel",
  "Ночной Охотник": "Night Stalker",
  "Автотроника Турбо": "Autotronic Turbo",
  "Африканская Сетка Тролль": "Safari Mesh Meme",
  "Вулкан и Огонь": "Vulcan & Fire",
  "Изумрудный Рай": "Emerald Paradise",
  "Мраморный Градиент": "Marble Fade God",
  "Гамма Волны": "Gamma Waves",
  "Аниме & Вайфу": "Anime & Waifu Case",
  "Нео-Нуар Синдикат": "Neo-Noir Syndicate",
  "Золотой Люкс": "Golden Luxury",
  "Мифический Лор": "Mythic Lore",
  "Звери & Монстры": "Beasts & Monsters",
  "Киберпанк 2077": "Cyberpunk 2077",
  "Красный Инвентарь": "All Red Inventory",
  "Синий Инвентарь": "All Blue Inventory",
  "Зеленый Инвентарь": "All Green Inventory",
  "Фиолетовый Инвентарь": "All Purple Inventory",
  "Белоснежный Инвентарь": "All White Inventory",
  "Черный Стелс": "Black Stealth Inventory",
  "Король Пистолетов": "King of Pistols",
  "AWP Властелин": "AWP Overlord",
  "AK-47 Император": "AK-47 Emperor",
  "Битва M4A4 и M4A1-S": "M4A4 vs M4A1-S Clash",
  "Бог Скорострелок": "God of SMGs",
  "Дробовики & Пулеметы": "Shotguns & Machineguns",
  "Kilowatt Электрошок": "Kilowatt Electric",
  "Грезы и Кошмары": "Dreams & Nightmares",
  "Мастер Отдачи": "Recoil Master",
  "Вайб Революции": "Revolution Vibe",
  "Разлом Анархия": "Fracture Anarchy",
  "Призма Всплеск Цвета": "Prisma Splash",
  "Запретная Зона": "Danger Zone Case",
  "Клатч Раунд": "Clutch Round",
  "Горизонт Рассвет": "Horizon Sunrise",
  "Спектр Радуга": "Spectrum Rainbow",
  "Коллекция Перчаток": "Glove Collector",
  "Перчатки Specialist": "Specialist Gloves",
  "Перчатки Moto Гонщик": "Moto Racer Gloves",
  "Перчатки Водителя Driver": "Driver Gloves",
  "Обмотки Рук Hand Wraps": "Hand Wraps Rebel",
  "Арена Bloodsport": "Bloodsport Arena",
  "Меха Будущее": "Mecha Future",
  "Они Самурай": "Oni Samurai",
  "Вода & Лед": "Water & Ice",
  "Токсичная Радиация": "Toxic Hazard",
  "Ретро Синтвейв": "Retro Synthwave",
  "Древний Египет": "Ancient Egypt",
  "Скандинавские Боги": "Norse Gods",
  "Сен-Марк Тропики": "St. Marc Tropics",
  "Каналы Венеции": "Venice Canals",
  "Восходящее Солнце": "Rising Sun Japan",
  "Боги и Чудовища": "Gods and Monsters",
  "Автомастерская Chop Shop": "Chop Shop Workshop",
  "Спецназ Альфа": "Alpha Special Forces",
  "Штурм Ассалт": "Assault Ops",
  "Армейское Золото": "Mil-Spec Gold",
  "Секретная Служба 007": "Secret Service 007",
  "Кейс «Легенда Howl»": "Howl Legend Case",
  "Кейс «Вулкан & Огонь»": "Vulcan & Fire Strike",
  "Кейс «Золотой Век»": "Golden Age Case",
  "Кейс «Градиентный Раш»": "Fade Rush Case",
  "Кейс «Хранилище Перчаток»": "Glove Vault Case",
  "Кейс «Галактика Допплер»": "Doppler Galaxy Case",
  "Кейс «Дикий Лотос»": "Wild Lotus Case",
  "Кейс «Огненный Змей»": "Fire Serpent Case",
  "Кейс «Неоновая Революция»": "Neon Revolution Case",
  "Кейс «Снайперская Элита»": "Sniper Elite Case",
  "Кейс «Грааль CS2»": "CS2 Grail Case",
  "Кейс «Рулетка Ножей»": "Knife Roulette Case",
  "Кейс «Ярость Redline»": "Redline Fury Case",
  "Кейс «Матрица Овердрайв»": "Matrix Overdrive Case",
  "Кейс «Токио Дрифт»": "Tokyo Drift Case",
  "Кейс «Тактический Спецназ»": "Tactical Force Case",
  "Кейс «Роял Флеш»": "Royal Flush Case",
  "Кейс «Суперпроводник»": "Superconductor Case",
  "Кейс «Лед & Пламя»": "Ice & Fire Case",
  "Кейс «Темное Фэнтези»": "Dark Fantasy Case",
  "Кейс «Bubblegum Мечта»": "Bubblegum Dream Case",
  "Кейс «Уличный Граффити»": "Street Graffiti Case",
  "Кейс «Кибер-Ниндзя»": "Cyber Ninja Case",
  "Кейс «Королевская Охота»": "Royal Hunt Case",
  "Кейс «Тайный Арсенал»": "Covert Arsenal Case",
  "Кейс «Космическая Одиссея»": "Space Odyssey Case",
  "Кейс «Дыхание Дракона»": "Dragon Breath Case",
  "Кейс «Кибер-Самурай»": "Cyber Samurai Case",
  "Кейс «Глитч Протокол»": "Glitch Protocol Case",
  "Кейс «Атомный Распад»": "Atomic Decay Case",
  "Кейс «Адское Пламя»": "Inferno Heat Case",
  "Кейс «Полярная Вьюга»": "Arctic Blizzard Case",
  "Кейс «Хищник Джунглей»": "Jungle Predator Case",
  "Кейс «Секретные Операции X»": "Covert Ops X Case",
  "Кейс «Неоновый Токио»": "Neon Tokyo Case",
  "Кейс «Долина Вальхаллы»": "Valhalla Valley Case",
  "Кейс «Золотой Арабеск»": "Gold Arabesque Case",
  "Кейс «Полуночный Гонщик»": "Midnight Rider Case",
  "Кейс «Ретровейв 80-х»": "80s Retrowave Case",
  "Кейс «Квантовое Ядро»": "Quantum Core Case",
  "Кейс «Багровая Династия»": "Crimson Dynasty Case",
  "Кейс «Изумрудный Дворец»": "Emerald Palace Case",
  "Кейс «Теневой Ассасин»": "Shadow Assassin Case",
  "Кейс «Возрождение Феникса»": "Phoenix Rebirth Case",
  "Кейс «Гипер-Скорость»": "Hyper Velocity Case",
  "Кейс «Бездна Океана»": "Abyssal Depths Case",
  "Кейс «Снайперский Дозор»": "Sniper Watch Case",
  "Кейс «Хранилище Титанов»": "Titan Vault Case",
  "Кейс «Карамельный Раш»": "Candy Rush Case",
  "Кейс «Бриллиантовый Джекпот»": "Diamond Jackpot Case",
  "Запечатанный терминал «Генезис»": "Sealed Genesis Terminal",
  "Запечатанный терминал «Мёртвая рука»": "Sealed Dead Hand Terminal",
  "Кейс «Галерея»": "The Gallery Case",
  "Кейс «Лихорадка»": "The Fever Case",
  "Коллекция «Overpass 2024»": "The Overpass 2024 Collection",
  "Коллекция «Спорт и отдых»": "The Sport & Field Collection",
  "Коллекция «Графика»": "The Graphic Collection",
  "Кейс «Термообработка»": "Heat Treated Limited Edition",
  "Коллекция «Шпионские технологии»": "Spy Tech 2026 Collection",
  "Коллекция «Арабеска Востока»": "Arabesque 2026 Collection",
  "Ферма": "Farm",
  "Кейс «Кибер-Протокол»": "Cyber Protocol Case",
  "Кейс «Раш Банана на Inferno»": "Inferno Banana Rush Case",
  "Кейс «Золотой Слиток 24K»": "24K Gold Bar Case",
  "Кейс «Квантовое Измерение»": "Quantum Dimension Case",
  "Кейс «Обезьяний Бизнес»": "Monkey Business Case",
  "Кейс «Меха-Овердрайв»": "Mecha Overdrive Case",
  "Кейс «Токсичная Угроза Biohazard»": "Toxic Biohazard Case",
  "Кейс «Казино Джекпот Ultra»": "Casino Jackpot Ultra Case",
  "Кейс «Nano Banana Киберпанк»": "Nano Banana Cyber Case",
  "Кейс «Nano Banana 24K Золото»": "Nano Banana 24K Gold Case",
  "Кейс «Квантовый Банан»": "Quantum Banana Case",
  "Кейс «Monkey Business & Бананы»": "Monkey Business & Bananas Case",
  "Кейс «Меха-Банан Овердрайв»": "Mecha Banana Overdrive Case",
  "Кейс «Токсичный Банан Biohazard»": "Toxic Banana Biohazard Case",
  "Кейс «Джекпот Банана Ultra»": "Banana Jackpot Ultra Case"
};
